// <auto-generated />
using MServices.Domain.Infra.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MServices.Domain.Migrations
{
    [DbContext(typeof(FrotaContext))]
    partial class FrotaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MServices.Domain.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Chassi")
                        .HasColumnType("nvarchar(17)")
                        .HasMaxLength(17);

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("QuantidadePassageiros")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.HasKey("Id", "Chassi");

                    b.ToTable("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
