//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MServices.Domain.Menssages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Excecoes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Excecoes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MServices.Domain.Menssages.Excecoes", typeof(Excecoes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao tentar cadastrar o veículo. Por favor, tente novamente!.
        /// </summary>
        public static string Fail_Register_Vehicle {
            get {
                return ResourceManager.GetString("Fail_Register_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível apagar o veículo informado. Por favor, tente novamente!.
        /// </summary>
        public static string Fail_Remove_Vehicle {
            get {
                return ResourceManager.GetString("Fail_Remove_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve falha ao fazer a consulta de veículos. Por favor, tente novamente!.
        /// </summary>
        public static string Fail_Search_Vehicles {
            get {
                return ResourceManager.GetString("Fail_Search_Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível atualizar os novos dados do veículo nesse momento. Por favor, tente novamente!.
        /// </summary>
        public static string Fail_Update_Vehicle {
            get {
                return ResourceManager.GetString("Fail_Update_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Id: {0} não localizado no banco de dados. Verifique&quot;.
        /// </summary>
        public static string ID_NotFound {
            get {
                return ResourceManager.GetString("ID_NotFound", resourceCulture);
            }
        }
    }
}
